In [1]:
from pykonker.main.api import Client

In [2]:
import pandas as pd
import geopandas as gpd

In [3]:
konker = Client()

In [4]:
username = 'radix@konkerlabs.com'
pwd = '2ZLbCU4DmzxvMYud'
konker.login(username=username, password=pwd)

(<requests_oauthlib.oauth2_session.OAuth2Session at 0x116556a58>,
 {'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ0cnVzdCIsInJlYWQiLCJ3cml0ZSJdLCJleHAiOjE5MTE2NjE3MjQsImF1dGhvcml0aWVzIjpbIkxJU1RfQUxFUlRfVFJJR0dFUlMiLCJSRU1PVkVfREVWSUNFX0NPTkZJRyIsIkVESVRfQUxFUlRfVFJJR0dFUiIsIkNSRUFURV9PQVVUSCIsIkxJU1RfTE9DQVRJT05TIiwiRURJVF9ERVZJQ0VfTU9ERUwiLCJTSE9XX0dBVEVXQVkiLCJBRERfVVNFUiIsIkNSRUFURV9MT0NBVElPTiIsIkxJU1RfREVWSUNFUyIsIlNIT1dfREVWSUNFX1JPVVRFIiwiRURJVF9UUkFOU0ZPUk1BVElPTiIsIlNIT1dfVFJBTlNGT1JNQVRJT04iLCJTSE9XX1JFU1RfREVTVElOQVRJT04iLCJDUkVBVEVfVFJBTlNGT1JNQVRJT04iLCJTSE9XX0FMRVJUX1RSSUdHRVIiLCJSRU1PVkVfREVWSUNFIiwiTE9HSU4iLCJWSUVXX0RFVklDRV9MT0ciLCJSRU1PVkVfUkVTVF9ERVNUSU5BVElPTiIsIlJFTU9WRV9ERVZJQ0VfTU9ERUwiLCJMT0dPVVQiLCJBRERfQVBQTElDQVRJT04iLCJTSE9XX1VTRVIiLCJMSVNUX0FQUExJQ0FUSU9OIiwiTUFSS19VU0VSX05PVElGSUNBVElPTl9BU19SRUFEIiwiTElTVF9VU0VSIiwiQ1JFQVRFX0RFVklDRV9ST1VURSIsIlNIT1dfREVWSUNFX01PREVMIiwiU0hPV19QUklWQVRFX1NUT1JBR0UiLCJSRU1PVkVfVVNFUiIsIlNIT1dfQVBQTElDQVRJT04iLCJSRU1PVkVfRU5SSUNITUVOVCIsIlNIT1dfREVWSUNFIiwiUkVNT1ZFX0RFVklDRV9ST1VURSIsIlJFTU9WRV9BUFBMSUNBVElPTiIsIlJFTU9WRV9UUkFOU0ZPUk1BVElPTiIsIkNSRUFURV9FTlJJQ0hNRU5UIiwiTElTVF9UUkFOU0ZPUk1BVElPTiIsIlZJRVdfVVNFUl9OT1RJRklDQVRJT05fTUVTU0FHRVMiLCJFRElUX0FQUExJQ0FUSU9OIiwiRURJVF9VU0VSIiwiQUREX0RFVklDRSIsIkxJU1RfRU5SSUNITUVOVCIsIkNSRUFURV9ERVZJQ0VfS0VZUyIsIkNSRUFURV9SRVNUX0RFU1RJTkFUSU9OIiwiTElTVF9ERVZJQ0VfQ09ORklHUyIsIkNSRUFURV9ERVZJQ0VfQ09ORklHIiwiUkVNT1ZFX0FMRVJUX1RSSUdHRVIiLCJDUkVBVEVfREVWSUNFX01PREVMIiwiTElTVF9ST1VURVMiLCJTSE9XX0RFVklDRV9DT05GSUciLCJSRU1PVkVfUFJJVkFURV9TVE9SQUdFIiwiQUREX1BSSVZBVEVfU1RPUkFHRSIsIkVESVRfREVWSUNFIiwiRURJVF9ERVZJQ0VfUk9VVEUiLCJSRU1PVkVfTE9DQVRJT04iLCJWSUVXX0RFVklDRV9DSEFSVCIsIkVESVRfRU5SSUNITUVOVCIsIkxJU1RfR0FURVdBWVMiLCJFRElUX09XTl9VU0VSX1BST0ZJTEUiLCJWSUVXX1VTRVJfUFJPRklMRSIsIkVESVRfTE9DQVRJT04iLCJTSE9XX0xPQ0FUSU9OIiwiTElTVF9PQVVUSCIsIkVESVRfUkVTVF9ERVNUSU5BVElPTiIsIlNIT1dfRU5SSUNITUVOVCIsIkVESVRfUFJJVkFURV9TVE9SQUdFIiwiQ1JFQVRFX0FMRVJUX1RSSUdHRVIiLCJMSVNUX0RFVklDRV9NT0RFTCIsIkNIQU5HRV9PV05fUEFTU1dPUkQiLCJFRElUX0RFVklDRV9DT05GSUciLCJFRElUX0dBVEVXQVkiLCJFWFBPUlRfREVWSUNFX0NTViIsIkNSRUFURV9HQVRFV0FZIiwiTElTVF9SRVNUX0RFU1RJTkFUSU9OUyIsIlJFTU9WRV9HQVRFV0FZIiwiUkVNT1ZFX09BVVRIIiwiUk9MRV9JT1RfVVNFUiJdLCJqdGkiOiJmODA4YjY4YzAzNjI0YjExOTFmZjcyYmQ4YTljZTkwZjEwN2EwZGM4MjUxYjQ1MzNhYzg1NTZlYTMxMThiMTk0OWZhYTE3ZjRkMmI5NDE0ZjkxODc3OTY3N2M0MDhiNGUiLCJjbGllbnRfaWQiOiJyYWRpeEBrb25rZXJsYWJzLmNvbSJ9.JHIJ2V6sHtCCdVy7xvUcbs8g28fPUk61lGU2Bal5p3k',
  'token_type': 'bearer',
  'expires_in': 311551593,
  'scope': ['trust', 'read', 'write'],
  'jti': 'f808b68c03624b1191ff72bd8a9ce90f107a0dc8251b4533ac8556ea3118b1949faa17f4d2b9414f918779677c408b4e',
  'expires_at': 1911661724.1848252})

In [5]:
apps = pd.json_normalize(konker.get_applications())

{'timestamp': 1600110147, 'code': 200, 'status': 'success', 'result': [{'friendlyName': 'uhhn53st', 'description': None, 'name': 'uhhn53st'}, {'friendlyName': 'globo', 'description': 'devices do projeto da globo de tracking de veiculos eletricos', 'name': 'globo'}]}

In [6]:
apps

  friendlyName                                        description      name
0     uhhn53st                                               None  uhhn53st
1        globo  devices do projeto da globo de tracking de vei...     globo

In [9]:
konker.set_application('globo')
devices = pd.json_normalize(konker.get_all_devices())

In [10]:
devices

,id,name,description,locationName,deviceModelName,active,debug,tags,guid
0,865083031014764,865083031014764,None,default,default,True,False,[],f6bef9f0-9cca-4cdd-9447-ce226ee90842
1,865083031013154,865083031013154,None,default,default,True,False,[],90a20c97-7572-48ee-a2fb-ca65298eff77
2,865083031015928,865083031015928,None,default,default,True,False,[],f34919f4-1462-4cdf-8fce-6a0db6caaecd
3,865083031016884,865083031016884,None,default,default,True,False,[],bcb806e4-3ac6-45cf-99d7-c3b0a79da3a4
4,865083031015688,865083031015688,None,default,default,True,False,[],861ed2ef-9d61-435a-b09c-23ef8ee9a19b
5,865083031018088,865083031018088,None,default,default,True,False,[],d06066ed-2718-48b8-962b-c79a418b8b00
6,865083031027774,865083031027774,None,default,default,True,False,[],cd4a9505-dbd6-4227-a8b4-34e5cd8390e4
7,865083031017973,865083031017973,None,default,default,True,False,[],874b344e-123f-4c15-afb4-8a610aa2a06e
8,865083031014699,865083031014699,None,default,default,True,False,[],7f625eee-56f5-45f4-ac52-84155e2ec6a4
9,865083031017205,865083031017205,None,default,default,True,False,[],7609ce01-6b79-41dc-816a-35e51673ffa0

In [11]:
# help
data = pd.json_normalize(konker.read_data(guid='f6bef9f0-9cca-4cdd-9447-ce226ee90842'))

Reading channel(f6bef9f0-9cca-4cdd-9447-ce226ee90842.None) from 2020-09-04T00:00:00-03:00 XX....
Done

In [12]:
data

,timestamp,ingestedTimestamp,incoming.deviceGuid,incoming.channel,geolocation.lat,geolocation.lon,payload._lon,payload.gpsSignal,payload.distance,payload.channel,...,payload.attr.hdop,payload.attr.ignition,payload.attr.odometer,payload.battery,payload.attr.power,payload.attr.batteryLevel,payload.attr.input,payload.attr.output,payload.attr.rpm,payload.attr.fuel
0,2020-09-09T16:48:45.451Z,2020-09-09T16:48:45.550Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.961768,-43.406777,-43.406777,-1,0.00,location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-09-09T16:48:17Z,2020-09-10T11:17:47.996Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.961742,-43.406803,-43.406803,-1,3.93,location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-09-09T16:48:14Z,2020-09-09T16:48:14.600Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.961768,-43.406777,-43.406777,-1,0.00,location,...,0.0,False,400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-09-09T16:48:12Z,2020-09-09T16:48:15.357Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.961768,-43.406777,-43.406777,-1,0.00,location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-09-09T16:48:12Z,2020-09-09T16:48:17.107Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.961768,-43.406777,-43.406777,-1,0.00,location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6368,2020-09-14T15:13:57Z,2020-09-14T15:15:57.014Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.960075,-43.402445,-43.402445,-1,125.35,location,...,1.0,True,34400.0,100.0,12.823,100.0,129.0,0.0,19.0,20.0
6369,2020-09-14T15:13:48Z,2020-09-14T15:15:56.016Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.959963,-43.402530,-43.402530,-1,139.90,location,...,1.0,True,34400.0,100.0,12.823,100.0,129.0,0.0,19.0,21.0
6370,2020-09-14T15:13:45Z,2020-09-14T15:15:43.988Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.959882,-43.402615,-43.402615,-1,138.27,location,...,1.0,True,34300.0,100.0,12.821,100.0,129.0,0.0,19.0,22.0
6371,2020-09-14T15:13:39Z,2020-09-14T15:16:08.030Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.959682,-43.402627,-43.402627,-1,174.07,location,...,1.0,True,34300.0,100.0,12.821,100.0,129.0,0.0,19.0,22.0
6372,2020-09-14T03:50:47.341Z,2020-09-14T03:50:47.679Z,f6bef9f0-9cca-4cdd-9447-ce226ee90842,location,-22.958202,-43.404258,-43.404258,-1,0.00,location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN